# Generated by Django 5.1.8 on 2026-03-21 19:23

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='German', max_length=40)),
                ('article', models.CharField(blank=True, default='', max_length=8)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=160)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('language', 'article', 'word')},
            },
        ),
        migrations.CreateModel(
            name='UserImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('score_delta', models.IntegerField(default=0)),
                ('encrypted_note', core.fields.EncryptedTextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_language', models.CharField(default='German', max_length=40)),
                ('current_level', models.CharField(default='A1.1', max_length=20)),
                ('weekly_goal', models.CharField(default='5 lessons', max_length=40)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('encrypted_notes', core.fields.EncryptedTextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('learned', 'Learned')], default='new', max_length=16)),
                ('mastery_score', models.PositiveSmallIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learningword')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
