# Generated by Django 5.1.8 on 2026-03-22 21:39

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='llm_api_key',
            field=core.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_model',
            field=models.CharField(default='lumina', max_length=20),
        ),
    ]
